language: python
python: 3.7
dist: xenial
sudo: true

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
